### PR TITLE
Unpack main

### PR DESCRIPTION
**Pull request by activescott**
Adding this pull for visibility...

Below immediate tasks checked ✔️ 
- [x] Test it
- [x] Ensure main is re-generated with the latest at https://github.com/activescott/lovlify
- [x] Consider doing trades too (or maybe do this in a separate PR?)
  - I consider it and I think it will work but should be a separate PR. This already introduces a TON of changes.
- [x] Re-do the directContractLinkWarning PR from FD? Doesn't appear to be in the main-unminified.
  - I must have used an outdated version of the main-unpacked.js to unpack at one point. I restored the existing main-unpacked.js from this repo and the directContractLinkWarning code was there.
- [ ] Close the related issue #29

Mostly a note for myself. To re-do the unpacking take the following steps:
- Clone latest https://github.com/activescott/lovlify
- do `yarn link` in the lovlify directory
- do `yarn link lovlify` in the frontend directory
- run `lovlify scripts/_old_main_packed_modules.js`
- `cp -R ./scripts/_old_main_packed_modules.js-lovlify/ ./js/`
- `mv js/ROOT_APP_MODULE.js js/main.js`

To rebuild for a prod deployment:
- `yarn build`
First time after lovlify you get:
> ERROR in ./js/main.js
> Module not found: Error: Can't resolve '../server/utility.js' in '/Users/scott/src/agorex/FrontEnd/js'
> @ ./js/main.js 88:14-45

To fix, go into main.js and change `utility = require("../server/utility.js"),` to `utility = require("./server/utility"), 
To run dev locally:
- `yarn start` # with hotreload

### CODE REVIEW

**Comment by JonathonDunford** [comment]
@activescott 

You requested a review a few days ago, but the todo list is incomplete. Do you still want me to review this?

**Comment by activescott** [comment]
@JonathonDunford Sorry for my delay here. Still recovering here. I did work on this today though and made some progress cleaning it up. Ran into some trouble with json that I'm working through.

**Comment by activescott** [comment]
btw progress is being made in https://github.com/activescott/lovlify which I'm now using to do this in a more thorough manner.

**Comment by activescott** [comment]
@JonathonDunford Please give this a look on your side. Run it locally and do some testing and let me know if you see anything.

**Review by Ebonsignori — APPROVED** [review]

**Review by Ebonsignori — APPROVED** [review]
Incredibly useful stuff. I now see why using the old frontend could have been an option. The code may still difficult to work with, but it's much much better than working with the previous main.js

**Comment by activescott** [comment]
I think this is worth merging as a reference. To be clear though I think the right long term option for Agorex is to write a new front end.

**Pull request merged**
